#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

trap "rm -f ./commitlint.config.js" EXIT
echo "module.exports = {extends: ['@commitlint/config-conventional']};" > commitlint.config.js
yarn commitlint --edit $1
